const Q=[
["Thailand","choice","Which countries share a land border with Thailand?","ประเทศใดมีพรมแดนทางบกติดกับประเทศไทย?",[["Laos, Cambodia, Malaysia, Myanmar","ลาว กัมพูชา มาเลเซีย เมียนมา"],["Laos, Vietnam, China, Malaysia","ลาว เวียดนาม จีน มาเลเซีย"],["Cambodia, Indonesia, Myanmar, Laos","กัมพูชา อินโดนีเซีย เมียนมา ลาว"],["Malaysia, Singapore, Vietnam, Myanmar","มาเลเซีย สิงคโปร์ เวียดนาม เมียนมา"]],0],
["Thailand","choice","The Mekong River forms part of Thailand's border with which country?","แม่น้ำโขงเป็นส่วนหนึ่งของพรมแดนไทยกับประเทศใด?",[["Malaysia","มาเลเซีย"],["Laos","ลาว"],["Myanmar","เมียนมา"],["Singapore","สิงคโปร์"]],1,"🌊"],
["Thailand","choice","Nong Bua Lamphu is in which region of Thailand?","หนองบัวลำภูอยู่ในภูมิภาคใดของประเทศไทย?",[["North","ภาคเหนือ"],["Northeast / Isan","ภาคตะวันออกเฉียงเหนือ / อีสาน"],["Central","ภาคกลาง"],["South","ภาคใต้"]],1],
["Thailand","choice","Ayutthaya was historically what?","อยุธยาในอดีตเคยเป็นอะไร?",[["An ancient capital","ราชธานีโบราณ"],["A southern island","เกาะทางภาคใต้"],["A modern industrial city only","เมืองอุตสาหกรรมสมัยใหม่เท่านั้น"],["A mountain kingdom outside Thailand","อาณาจักรบนภูเขานอกประเทศไทย"]],0],
["Thailand","choice","Songkran is traditionally connected with what?","สงกรานต์ตามประเพณีเกี่ยวข้องกับอะไร?",[["Thai New Year","วันปีใหม่ไทย"],["Harvesting rice only","การเก็บเกี่ยวข้าวเท่านั้น"],["A military holiday","วันหยุดทางทหาร"],["The start of winter","การเริ่มต้นฤดูหนาว"]],0],
["Thailand","choice","Who normally leads Thailand's day-to-day government?","โดยทั่วไปใครเป็นผู้นำการบริหารรัฐบาลไทยในแต่ละวัน?",[["Prime Minister","นายกรัฐมนตรี"],["Governor of Bangkok","ผู้ว่าราชการกรุงเทพฯ"],["Chief judge","ประธานศาล"],["Army commander automatically","ผู้บัญชาการทหารโดยอัตโนมัติ"]],0],
["UK & Wales","choice","Which four countries make up the United Kingdom?","สหราชอาณาจักรประกอบด้วย 4 ประเทศใด?",[["England, Scotland, Wales, Northern Ireland","อังกฤษ สกอตแลนด์ เวลส์ ไอร์แลนด์เหนือ"],["England, Wales, Ireland, France","อังกฤษ เวลส์ ไอร์แลนด์ ฝรั่งเศส"],["England, Scotland, Wales, Republic of Ireland","อังกฤษ สกอตแลนด์ เวลส์ สาธารณรัฐไอร์แลนด์"],["Wales, Scotland, England, Iceland","เวลส์ สกอตแลนด์ อังกฤษ ไอซ์แลนด์"]],0],
["UK & Wales","choice","What is the capital city of Wales?","เมืองหลวงของเวลส์คือเมืองอะไร?",[["Swansea","สวอนซี"],["Cardiff","คาร์ดิฟฟ์"],["Bristol","บริสตอล"],["Liverpool","ลิเวอร์พูล"]],1],
["UK & Wales","flags","Which flag belongs to Wales?","ธงใดเป็นธงของเวลส์?",[["Wales","เวลส์","walesFlag"],["Thailand","ไทย","thaiFlag"],["Japan","ญี่ปุ่น","japanFlag"],["Sweden","สวีเดน","swedenFlag"]],0],
["UK & Wales","choice","Which area is mainly managed by the Welsh Government in Wales?","เรื่องใดส่วนใหญ่บริหารโดยรัฐบาลเวลส์ในเวลส์?",[["Defence","กลาโหม"],["Foreign affairs","การต่างประเทศ"],["Health services","บริการสาธารณสุข"],["UK passports","หนังสือเดินทางสหราชอาณาจักร"]],2,null,true],
["UK & Wales","choice","The UK Parliament meets in which city?","รัฐสภาสหราชอาณาจักรประชุมที่เมืองใด?",[["Cardiff","คาร์ดิฟฟ์"],["London","ลอนดอน"],["Edinburgh","เอดินบะระ"],["Belfast","เบลฟาสต์"]],1],
["World","choice","Which is the largest continent by land area?","ทวีปใดมีพื้นที่ใหญ่ที่สุด?",[["Africa","แอฟริกา"],["Asia","เอเชีย"],["Europe","ยุโรป"],["South America","อเมริกาใต้"]],1],
["World","choice","Which country has the largest population?","ประเทศใดมีประชากรมากที่สุด?",[["India","อินเดีย"],["Thailand","ไทย"],["Japan","ญี่ปุ่น"],["United Kingdom","สหราชอาณาจักร"]],0],
["World","choice","What does the Equator divide Earth into?","เส้นศูนย์สูตรแบ่งโลกออกเป็นอะไร?",[["East and west only","ตะวันออกและตะวันตกเท่านั้น"],["Northern and Southern Hemispheres","ซีกโลกเหนือและซีกโลกใต้"],["Land and ocean","พื้นดินและมหาสมุทร"],["Hot and cold countries","ประเทศร้อนและประเทศหนาว"]],1,null,true],
["World","choice","Why can it be daytime in Thailand while it is night somewhere else?","ทำไมประเทศไทยอาจเป็นเวลากลางวันในขณะที่อีกประเทศเป็นกลางคืน?",[["Earth rotates","โลกหมุนรอบตัวเอง"],["The Sun turns off","ดวงอาทิตย์ดับ"],["The Moon blocks the Sun every night","ดวงจันทร์บังดวงอาทิตย์ทุกคืน"],["Clouds create night","เมฆทำให้เกิดกลางคืน"]],0],
["World","choice","What is one main purpose of the United Nations?","หนึ่งในจุดประสงค์หลักของสหประชาชาติคืออะไร?",[["International cooperation and peace","ความร่วมมือระหว่างประเทศและสันติภาพ"],["Running every country's police","ควบคุมตำรวจของทุกประเทศ"],["Choosing all national leaders","เลือกผู้นำของทุกประเทศ"],["Controlling world weather","ควบคุมสภาพอากาศโลก"]],0],
["World","choice","Which is the largest ocean?","มหาสมุทรใดใหญ่ที่สุด?",[["Atlantic","แอตแลนติก"],["Indian","อินเดีย"],["Pacific","แปซิฟิก"],["Arctic","อาร์กติก"]],2,"🌍"],
["Science","choice","Which organ pumps blood around the human body?","อวัยวะใดสูบฉีดเลือดไปทั่วร่างกาย?",[["Lungs","ปอด"],["Heart","หัวใจ"],["Liver","ตับ"],["Kidneys","ไต"]],1,"❤️"],
["Science","choice","Which travels faster?","อะไรเดินทางได้เร็วกว่า?",[["Sound","เสียง"],["Light","แสง"],["They are always the same","เร็วเท่ากันเสมอ"],["It depends only on colour","ขึ้นอยู่กับสีเท่านั้น"]],1],
["Science","choice","What mainly causes the seasons of the year?","อะไรเป็นสาเหตุหลักของฤดูกาล?",[["Earth's tilted axis","แกนโลกเอียง"],["Earth moving much closer to the Sun in summer","โลกเข้าใกล้ดวงอาทิตย์มากในฤดูร้อน"],["The Moon changing size","ดวงจันทร์เปลี่ยนขนาด"],["Clouds moving north and south","เมฆเคลื่อนขึ้นเหนือและใต้"]],0,null,true],
["Science","choice","At sea level, water boils at about what temperature?","ที่ระดับน้ำทะเล น้ำเดือดที่อุณหภูมิประมาณเท่าไร?",[["50°C","50°C"],["75°C","75°C"],["100°C","100°C"],["150°C","150°C"]],2],
["Science","choice","Plants use sunlight to make food in a process called…","พืชใช้แสงแดดสร้างอาหารในกระบวนการที่เรียกว่าอะไร?",[["Respiration","การหายใจ"],["Photosynthesis","การสังเคราะห์ด้วยแสง"],["Evaporation","การระเหย"],["Digestion","การย่อยอาหาร"]],1,null,true],
["Maths","choice","A shirt costs ฿800 and has 25% off. What is the new price?","เสื้อราคา 800 บาท ลด 25% ราคาใหม่เท่าไร?",[["฿500","500 บาท"],["฿600","600 บาท"],["฿650","650 บาท"],["฿700","700 บาท"]],1],
["Maths","choice","What number comes next: 3, 6, 12, 24, … ?","เลขถัดไปคืออะไร: 3, 6, 12, 24, … ?",[["30","30"],["36","36"],["48","48"],["54","54"]],2],
["Maths","choice","A journey is 180 km. At an average of 60 km/h, about how long does it take?","เดินทาง 180 กม. ด้วยความเร็วเฉลี่ย 60 กม./ชม. ใช้เวลาประมาณเท่าไร?",[["2 hours","2 ชั่วโมง"],["3 hours","3 ชั่วโมง"],["4 hours","4 ชั่วโมง"],["6 hours","6 ชั่วโมง"]],1],
["Maths","choice","Which fraction is larger?","เศษส่วนใดมีค่ามากกว่า?",[["2/3","2/3"],["3/4","3/4"],["They are equal","เท่ากัน"],["Impossible to compare","เปรียบเทียบไม่ได้"]],1,null,true],
["Maths","choice","You earn ฿12,000. Rent is ฿4,000 and food is ฿3,000. How much remains?","คุณมีรายได้ 12,000 บาท ค่าเช่า 4,000 และค่าอาหาร 3,000 เหลือเท่าไร?",[["฿3,000","3,000 บาท"],["฿4,000","4,000 บาท"],["฿5,000","5,000 บาท"],["฿6,000","6,000 บาท"]],2],
["Logic","choice","All roses are flowers. Some flowers are red. Can we definitely say some roses are red?","กุหลาบทุกดอกเป็นดอกไม้ และดอกไม้บางชนิดสีแดง เราสรุปได้แน่นอนหรือไม่ว่ากุหลาบบางดอกสีแดง?",[["Yes","ใช่"],["No","ไม่ใช่"],["Not enough information","ข้อมูลไม่เพียงพอ"],["Only in summer","เฉพาะฤดูร้อน"]],2,null,true],
["Logic","choice","Golf is taller than Boy. Boy is taller than Ant. Lotto is taller than Golf. Who is shortest?","กอล์ฟสูงกว่าบอย บอยสูงกว่าแอนท์ ล็อตโต้สูงกว่ากอล์ฟ ใครเตี้ยที่สุด?",[["Golf","กอล์ฟ"],["Boy","บอย"],["Ant","แอนท์"],["Lotto","ล็อตโต้"]],2],
["Logic","choice","What number comes next: 2, 3, 5, 8, 12, 17, … ?","เลขถัดไปคืออะไร: 2, 3, 5, 8, 12, 17, … ?",[["21","21"],["22","22"],["23","23"],["24","24"]],2,null,true],
["Logic","choice","A farmer has 17 chickens. All except 9 run away. How many remain?","ชาวนามีไก่ 17 ตัว ทุกตัวยกเว้น 9 ตัววิ่งหนีไป เหลือกี่ตัว?",[["8","8"],["9","9"],["17","17"],["26","26"]],1,null,true],
["Logic","emoji","Which one does NOT belong with the others?","ข้อใดไม่เข้าพวกกับข้ออื่น?",[["Apple","แอปเปิล","🍎"],["Banana","กล้วย","🍌"],["Orange","ส้ม","🍊"],["Car","รถยนต์","🚗"]],3],
["Logic","choice","Complete the pattern: ▲ ● ▲ ● ▲ …","เติมรูปแบบให้สมบูรณ์: ▲ ● ▲ ● ▲ …",[["▲","▲"],["●","●"],["■","■"],["◆","◆"]],1,"▲  ●  ▲  ●  ▲  ?"],
["Practical","choice","Your motorbike suddenly makes a strange new noise while riding. What is the best first response?","มอเตอร์ไซค์มีเสียงผิดปกติใหม่ขณะขี่ ควรทำอะไรก่อน?",[["Ride faster to test it","ขี่ให้เร็วขึ้นเพื่อทดสอบ"],["Stop somewhere safe and check it","หยุดในที่ปลอดภัยแล้วตรวจสอบ"],["Ignore it for several days","ไม่สนใจหลายวัน"],["Immediately buy a new bike","ซื้อคันใหม่ทันที"]],1],
["Practical","text","You have ฿3,000 left for 7 days. You still need food, petrol and phone credit. What would you do?","คุณเหลือเงิน 3,000 บาทสำหรับ 7 วัน และยังต้องซื้ออาหาร น้ำมัน และเครดิตโทรศัพท์ คุณจะวางแผนอย่างไร?"],
["Practical","choice","You see a shocking claim online. What is the best way to decide if it is true?","คุณเห็นข้อมูลที่น่าตกใจบนอินเทอร์เน็ต วิธีใดดีที่สุดในการตรวจสอบว่าจริงหรือไม่?",[["Share it immediately","แชร์ทันที"],["Believe it if many comments agree","เชื่อถ้ามีหลายคอมเมนต์เห็นด้วย"],["Check reliable sources and compare information","ตรวจสอบแหล่งข้อมูลที่น่าเชื่อถือและเปรียบเทียบข้อมูล"],["Believe it if the picture looks real","เชื่อถ้ารูปดูเหมือนจริง"]],2],
["Practical","choice","You miss the last bus you planned to take in an unfamiliar city. What should you do first?","คุณพลาดรถบัสเที่ยวที่วางแผนไว้ในเมืองที่ไม่คุ้นเคย ควรทำอะไรก่อน?",[["Panic and walk anywhere","ตกใจแล้วเดินไปเรื่อยๆ"],["Check safe alternative routes or transport","ตรวจสอบเส้นทางหรือการเดินทางทางเลือกที่ปลอดภัย"],["Turn your phone off","ปิดโทรศัพท์"],["Wait without checking anything","รอโดยไม่ตรวจสอบอะไร"]],1],
["Learning","slider","When learning something new, which feels more natural?","เวลาเรียนสิ่งใหม่ แบบไหนรู้สึกเป็นธรรมชาติมากกว่า?",["See it / ดูภาพ","Hear it / ฟัง"]],
["Learning","multi","Which topics are you genuinely interested in?","หัวข้อใดที่คุณสนใจจริงๆ?",[["Sport","กีฬา"],["Money & business","เงินและธุรกิจ"],["Cars & motorbikes","รถยนต์และมอเตอร์ไซค์"],["Travel & countries","ท่องเที่ยวและประเทศต่างๆ"],["Music","ดนตรี"],["Games","เกม"],["Food","อาหาร"],["Animals","สัตว์"],["Science","วิทยาศาสตร์"],["History","ประวัติศาสตร์"],["Computers","คอมพิวเตอร์"]]],
["Learning","choice","If you do not understand a teacher, what do you usually do?","ถ้าคุณไม่เข้าใจครู คุณมักทำอย่างไร?",[["Ask again","ถามอีกครั้ง"],["Pretend I understand","ทำเป็นว่าเข้าใจ"],["Search for the answer myself","ค้นหาคำตอบเอง"],["Give up","เลิกทำ"]]],
["Learning","slider","How comfortable are you when someone corrects your English?","คุณรู้สึกสบายใจแค่ไหนเมื่อมีคนแก้ภาษาอังกฤษให้?",["Very uncomfortable / ไม่สบายใจมาก","Very comfortable / สบายใจมาก"]],
["Learning","choice","Which way would you most enjoy learning English?","คุณอยากเรียนภาษาอังกฤษแบบไหนมากที่สุด?",[["Short videos","วิดีโอสั้น"],["Conversation","การสนทนา"],["Games and quizzes","เกมและแบบทดสอบ"],["Reading and writing","อ่านและเขียน"]]]
];

let i=0,answers=Array(Q.length).fill(null);
const $=s=>document.querySelector(s);
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active")}
function render(){
 const q=Q[i]; $("#category").textContent=q[0];$("#questionEn").textContent=q[2];$("#questionTh").textContent=q[3];$("#counter").textContent=(i+1)+" / "+Q.length;$("#progressFill").style.width=((i+1)/Q.length*100)+"%";$("#challenge").style.display=q[7]?"block":"none";$("#backBtn").style.visibility=i?"visible":"hidden";
 const media=$("#media");media.innerHTML=q[6]?'<div class="visual"><div class="big">'+q[6]+'</div></div>':"";
 const area=$("#answerArea");area.innerHTML="";
 if(q[1]==="choice"){
  const box=document.createElement("div");box.className="choices";
  q[4].forEach((a,n)=>{const b=document.createElement("button");b.className="choice"+(answers[i]===n?" selected":"");b.innerHTML='<span class="letter">'+String.fromCharCode(65+n)+'</span><span><b>'+a[0]+'</b><small>'+a[1]+'</small></span>';b.onclick=()=>{answers[i]=n;render()};box.appendChild(b)});area.appendChild(box)
 }else if(q[1]==="flags"){
  const g=document.createElement("div");g.className="image-grid";q[4].forEach((a,n)=>{const b=document.createElement("button");b.className="img-choice"+(answers[i]===n?" selected":"");b.innerHTML='<div class="img-box"><div class="flag '+a[2]+'"></div></div><b>'+a[0]+'</b><br><small>'+a[1]+'</small>';b.onclick=()=>{answers[i]=n;render()};g.appendChild(b)});area.appendChild(g)
 }else if(q[1]==="emoji"){
  const g=document.createElement("div");g.className="image-grid";q[4].forEach((a,n)=>{const b=document.createElement("button");b.className="img-choice"+(answers[i]===n?" selected":"");b.innerHTML='<div class="img-box">'+a[2]+'</div><b>'+a[0]+'</b><br><small>'+a[1]+'</small>';b.onclick=()=>{answers[i]=n;render()};g.appendChild(b)});area.appendChild(g)
 }else if(q[1]==="text"){
  const t=document.createElement("textarea");t.className="textbox";t.placeholder="Answer in Thai or English… / ตอบเป็นภาษาไทยหรืออังกฤษก็ได้";t.value=answers[i]||"";t.oninput=e=>answers[i]=e.target.value;area.appendChild(t)
 }else if(q[1]==="slider"){
  const v=answers[i]??50;area.innerHTML='<div class="rangebox"><div class="rangeval">'+v+'</div><input id="rng" type="range" min="0" max="100" value="'+v+'"><div class="rangeheads"><span>'+q[4][0]+'</span><span>'+q[4][1]+'</span></div></div>';$("#rng").oninput=e=>{answers[i]=+e.target.value;render()}
 }else if(q[1]==="multi"){
  const sel=answers[i]||[];const box=document.createElement("div");box.className="choices";q[4].forEach((a,n)=>{const b=document.createElement("button");b.className="choice"+(sel.includes(n)?" selected":"");b.innerHTML='<span class="letter">✓</span><span><b>'+a[0]+'</b><small>'+a[1]+'</small></span>';b.onclick=()=>{const s=new Set(answers[i]||[]);s.has(n)?s.delete(n):s.add(n);answers[i]=[...s];render()};box.appendChild(b)});area.appendChild(box)
 }
}
function results(){
 let cats={},correct=0,total=0;
 Q.forEach((q,n)=>{if(typeof q[5]==="number"){cats[q[0]]??={c:0,t:0};cats[q[0]].t++;total++;if(answers[n]===q[5]){cats[q[0]].c++;correct++}}});
 const pct=Math.round(correct/total*100);$("#scorePct").textContent=pct+"%";$("#scoreRing").style.setProperty("--pct",pct+"%");
 $("#headline").textContent=pct>=80?"Strong overall knowledge with good reasoning across several areas.":pct>=60?"A solid base with clear strengths and a few areas worth developing.":"Useful starting point: the profile shows where learning can be focused first.";
 $("#metrics").innerHTML=Object.entries(cats).map(([k,v])=>{const p=Math.round(v.c/v.t*100);return '<div class="metric"><div class="metrichead"><span>'+k+'</span><span>'+p+'%</span></div><div class="meter"><i style="width:'+p+'%"></i></div></div>'}).join("");
 const visual=answers[37]??50,comfort=answers[40]??50,method=answers[41];
 const meth=["Short videos","Conversation","Games & quizzes","Reading & writing"][method]||"Not selected";
 $("#learning").innerHTML='<p><b>Visual ↔ listening:</b> '+(visual<40?"leans visual":visual>60?"leans listening":"balanced")+'</p><p><b>Comfort with correction:</b> '+comfort+'/100</p><p><b>Preferred English method:</b> '+meth+'</p>';
 const ints=answers[38]||[];$("#interests").innerHTML=ints.length?ints.map(n=>'<span class="pill">'+Q[38][4][n][0]+'</span>').join(""):'<span class="pill">No interests selected</span>';
 const weakest=Object.entries(cats).sort((a,b)=>(a[1].c/a[1].t)-(b[1].c/b[1].t)).slice(0,2).map(x=>x[0]);
 $("#focus").innerHTML='<p>Start with <b>'+weakest.join(" and ")+'</b>, while using his stronger areas to keep lessons confident and interesting.</p><p>Keep English vocabulary separate from knowledge scoring, and revisit missed challenge questions later to see whether improvement comes from language or subject learning.</p>';
 window.summary='Sarun Discovery Lab\\nOverall knowledge: '+pct+'%\\n'+Object.entries(cats).map(([k,v])=>k+': '+Math.round(v.c/v.t*100)+'%').join('\\n')+'\\nLearning preference: '+(visual<40?"visual":visual>60?"listening":"balanced")+'\\nCorrection comfort: '+comfort+'/100\\nPreferred method: '+meth;
 show("results")
}
$("#startBtn").onclick=()=>{show("quiz");render()};$("#quitBtn").onclick=()=>show("landing");$("#backBtn").onclick=()=>{if(i>0){i--;render()}};$("#nextBtn").onclick=()=>{if(i<Q.length-1){i++;render()}else results()};$("#restartBtn").onclick=()=>{i=0;answers=Array(Q.length).fill(null);show("landing")};$("#copyBtn").onclick=async()=>{await navigator.clipboard.writeText(window.summary||"");$("#copyBtn").textContent="Copied ✓";setTimeout(()=>$("#copyBtn").textContent="Copy result summary",1200)};
